version: "3.9"

services:
  house-price-app:
    image: rithwik2005/house-price-app:latest
    container_name: house_price_prediction_app
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
